# Generated by Django 4.0.4 on 2022-04-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sended_at',
            new_name='sent_at',
        ),
    ]
