# Generated by Django 4.0.3 on 2022-04-10 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=120)),
                ('detalle', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'ciudades'},
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
