# Generated by Django 4.0.3 on 2022-04-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_promo_alter_city_options_city_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Post',
        ),
    ]
