# Generated by Django 4.0.3 on 2022-04-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(max_length=60),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
