# Generated by Django 4.0.4 on 2022-04-29 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_post_author_alter_post_city_delete_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='valid_through',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
